# Generated by Django 2.1.2 on 2018-10-13 04:57

from django.db import migrations, models
import wapyce.validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('base_url', models.URLField(unique=True, verbose_name='Base URL')),
                ('github_url', models.URLField(unique=True, validators=[wapyce.validation.validators.validate_github_url], verbose_name='Github repository')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
    ]
