# Generated by Django 2.1.2 on 2018-10-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='Close date')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validation.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Validation group',
            },
        ),
    ]
