# Generated by Django 2.1.2 on 2018-10-15 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('validation', '0002_validationgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'Canceled'), (2, 'Finished'), (3, 'Closed')], default=0, verbose_name='Validation status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validation.ValidationGroup', verbose_name='Validation group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
