# Generated by Django 2.1.2 on 2018-10-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(verbose_name='Page URL')),
                ('validation_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validation.Validation', verbose_name='Validation')),
            ],
            options={
                'verbose_name': 'Validated page',
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('validation_site', 'page_url')},
        ),
    ]
