# Generated by Django 2.1.2 on 2018-10-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_auto_20181016_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': 'Validation'},
        ),
    ]
