# Generated by Django 2.1.2 on 2018-10-20 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_auto_20181016_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Universally unique identifier'),
        ),
        migrations.AddField(
            model_name='validation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Universally unique identifier'),
        ),
        migrations.AddField(
            model_name='validationgroup',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Universally unique identifier'),
        ),
    ]
