# Generated by Django 2.1.2 on 2018-10-22 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_auto_20181020_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Universally unique identifier'),
        ),
    ]
