# Generated by Django 2.1.2 on 2018-10-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_auto_20181024_0300'),
        ('validation', '0007_page_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationgroup',
            name='site',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='group',
        ),
        migrations.AddField(
            model_name='validation',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='validation.Site', verbose_name='Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Started'), (1, 'Canceled'), (2, 'Finished')], default=0, verbose_name='Validation status'),
        ),
        migrations.DeleteModel(
            name='ValidationGroup',
        ),
    ]
