# Generated by Django 2.1.2 on 2018-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0008_auto_20181024_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deactivated')], default=0, verbose_name='Site status'),
        ),
    ]
