# Generated by Django 2.1.2 on 2018-10-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_issuepage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='selector',
            field=models.CharField(max_length=200, verbose_name='Selector'),
        ),
    ]
