# Generated by Django 2.1.2 on 2018-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0003_auto_20181023_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='context',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='issuepage',
            name='selector',
            field=models.CharField(blank=True, max_length=200, verbose_name='Selector'),
        ),
    ]
