# Generated by Django 2.1.2 on 2018-10-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_page_uuid'),
        ('notifier', '0002_auto_20181018_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubissue',
            name='validation_group',
        ),
        migrations.AddField(
            model_name='githubissue',
            name='validation_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='validation.Validation', verbose_name='Validation'),
            preserve_default=False,
        ),
    ]
