# Generated by Django 2.1.2 on 2018-10-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_auto_20181024_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubissue',
            name='validation_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='validation.Validation', verbose_name='Validation'),
        ),
    ]
