# Generated by Django 2.1.2 on 2018-10-18 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validation', '0005_auto_20181016_0414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(verbose_name='Approved')),
                ('date_feedback', models.DateTimeField(auto_now_add=True, verbose_name='Date of feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('validation_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validation.ValidationGroup', verbose_name='Validation group')),
            ],
            options={
                'verbose_name': 'Validations feedback',
            },
        ),
        migrations.AlterUniqueTogether(
            name='feedbackvalidation',
            unique_together={('validation_group', 'user')},
        ),
    ]
